# Generated by Django 4.2.30 on 2026-08-24 02:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('documento_identidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('ciudad', models.CharField(blank=True, max_length=120)),
                ('pais', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'destino',
                'verbose_name_plural': 'destinos',
                'ordering': ('pais', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=160)),
                ('descripcion', models.TextField(blank=True)),
                ('duracion_dias', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_base', models.DecimalField(decimal_places=2, help_text='Precio base por persona en USD.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='core.destino')),
            ],
            options={
                'verbose_name': 'paquete turístico',
                'verbose_name_plural': 'paquetes turísticos',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('cotizada', 'Cotizada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], db_index=True, default='solicitada', max_length=20)),
                ('fecha_salida', models.DateField(db_index=True)),
                ('fecha_regreso', models.DateField(blank=True, null=True)),
                ('cantidad_viajeros', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.cliente')),
                ('destino', models.ForeignKey(blank=True, help_text='Destino para una reserva personalizada sin paquete.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_personalizadas', to='core.destino')),
                ('paquete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='core.paqueteturistico')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ('nombre',),
            },
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('numero_pasaporte', models.CharField(blank=True, max_length=50, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=80)),
                ('es_titular', models.BooleanField(default=False)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajeros', to='core.reserva')),
            ],
            options={
                'verbose_name': 'viajero',
                'verbose_name_plural': 'viajeros',
                'ordering': ('apellidos', 'nombres'),
            },
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='paquetes', to='core.servicio'),
        ),
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.UniqueConstraint(fields=('nombre', 'ciudad', 'pais'), name='destino_ubicacion_unica'),
        ),
        migrations.AddConstraint(
            model_name='viajero',
            constraint=models.UniqueConstraint(fields=('reserva', 'numero_pasaporte'), name='viajero_pasaporte_unico_por_reserva'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('paquete__isnull', False), ('destino__isnull', False), _connector='OR'), name='reserva_paquete_o_destino'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('fecha_regreso__isnull', True), ('fecha_regreso__gte', models.F('fecha_salida')), _connector='OR'), name='reserva_fechas_validas'),
        ),
    ]
