# Generated by Django 4.2.30 on 2026-08-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudcontacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viajero',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
        migrations.DeleteModel(
            name='PaqueteTuristico',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
