# Generated by Django 4.2.30 on 2026-08-30 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def normalize_existing_requests(apps, schema_editor):
    SolicitudContacto = apps.get_model("core", "SolicitudContacto")
    for request in SolicitudContacto.objects.all():
        updates = []
        if "@" in request.contacto and not request.correo:
            request.correo = request.contacto
            updates.append("correo")
        if request.atendida:
            request.estado = "contactada"
            updates.append("estado")
        if updates:
            request.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sami_admin', '0010_lugarturistico_destacado_and_more'),
        ('core', '0003_remove_paqueteturistico_destino_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudcontacto',
            options={'ordering': ('estado', '-creado_en'), 'verbose_name': 'solicitud de contacto', 'verbose_name_plural': 'solicitudes de contacto'},
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='adultos',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='asignada_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='cotizacion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_origen', to='sami_admin.cotizacion'),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='edades_ninos',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='estado',
            field=models.CharField(choices=[('nueva', 'Nueva'), ('contactada', 'Contactada'), ('seguimiento', 'En seguimiento'), ('convertida', 'Convertida'), ('descartada', 'Descartada')], db_index=True, default='nueva', max_length=20),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='fecha_ida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='lugar_turistico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicas', to='sami_admin.lugarturistico'),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='ninos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='notas_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='origen',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='telefono',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='solicitudcontacto',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_publicas', to='sami_admin.tour'),
        ),
        migrations.RunPython(
            normalize_existing_requests,
            migrations.RunPython.noop,
        ),
    ]
