# Generated by Django 4.2.30 on 2026-08-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='aerolinea',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad_adultos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='cantidad_ninos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='equipaje_incluido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='escala_ida',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='escala_vuelta',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_ida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vuelta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hora_llegada_ida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hora_llegada_vuelta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hora_salida_ida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='hora_salida_vuelta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_importantes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ruta_vuelo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tipo_cotizacion',
            field=models.CharField(choices=[('vuelos', 'Vuelos'), ('tours', 'Tours'), ('vuelos_tours', 'Vuelos y Tours')], db_index=True, default='tours', max_length=20),
        ),
    ]
