# Generated by Django 4.2.30 on 2026-08-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0002_cotizacion_aerolinea_cotizacion_cantidad_adultos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='aerolinea',
            field=models.CharField(blank=True, choices=[('avianca', 'Avianca'), ('copa_airlines', 'Copa Airlines'), ('volaris', 'Volaris'), ('aeromexico', 'Aerom\u00e9xico'), ('american_airlines', 'American Airlines'), ('united_airlines', 'United Airlines'), ('delta', 'Delta'), ('spirit_airlines', 'Spirit Airlines'), ('iberia', 'Iberia'), ('otra', 'Otra')], max_length=30, null=True),
        ),
    ]
