# Generated by Django 4.2.30 on 2026-08-29 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0003_alter_cotizacion_aerolinea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('pais__nombre', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'país',
                'verbose_name_plural': 'países',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='duracion_tour',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='incluye',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='itinerario_resumido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='no_incluye',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='punto_encuentro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LugarTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('imagen', models.ImageField(upload_to='lugares_turisticos/')),
                ('descripcion_historica', models.TextField()),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lugares_turisticos', to='sami_admin.departamento')),
            ],
            options={
                'verbose_name': 'lugar turístico',
                'verbose_name_plural': 'lugares turísticos',
                'ordering': ('departamento__pais__nombre', 'departamento__nombre', 'nombre'),
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departamentos', to='sami_admin.pais'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='lugar_turistico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='sami_admin.lugarturistico'),
        ),
        migrations.AddConstraint(
            model_name='lugarturistico',
            constraint=models.UniqueConstraint(fields=('departamento', 'nombre'), name='lugar_turistico_unico_por_departamento'),
        ),
        migrations.AddConstraint(
            model_name='departamento',
            constraint=models.UniqueConstraint(fields=('pais', 'nombre'), name='departamento_unico_por_pais'),
        ),
    ]
