# Generated by Django 4.2.30 on 2026-08-29 23:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sami_admin', '0004_departamento_pais_cotizacion_duracion_tour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descripcion_historica_cotizada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='imagen_destino_cotizada',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_destino_cotizado',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_tour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='politica_cancelacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='que_llevar_tour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='recomendaciones_tour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='restricciones_tour',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='ubicacion_destino_cotizada',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vigencia_cotizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departamento',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='departamento',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lugares_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises_actualizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pais',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='pais',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=180)),
                ('duracion', models.CharField(max_length=120)),
                ('punto_encuentro', models.CharField(blank=True, max_length=255)),
                ('incluye', models.TextField()),
                ('no_incluye', models.TextField(blank=True)),
                ('itinerario', models.TextField()),
                ('recomendaciones', models.TextField(blank=True)),
                ('que_llevar', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('politica_cancelacion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours_creados', to=settings.AUTH_USER_MODEL)),
                ('lugar_turistico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='sami_admin.lugarturistico')),
            ],
            options={
                'ordering': ('lugar_turistico__nombre', 'nombre_comercial'),
            },
        ),
        migrations.CreateModel(
            name='HistorialCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=30)),
                ('estado', models.CharField(blank=True, max_length=12)),
                ('datos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='sami_admin.cotizacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historial de cotización',
                'verbose_name_plural': 'historial de cotizaciones',
                'ordering': ('-creado_en',),
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='sami_admin.tour'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.UniqueConstraint(fields=('lugar_turistico', 'nombre_comercial'), name='tour_unico_por_lugar'),
        ),
    ]
