# Generated by Django 4.2.30 on 2026-08-29 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0005_cotizacion_descripcion_historica_cotizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='archivada',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
