# Generated by Django 4.2.30 on 2026-08-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0006_cotizacion_archivada'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='nombre_tour_cotizado',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
