# Generated by Django 4.2.30 on 2026-08-30 00:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0007_cotizacion_nombre_tour_cotizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='edades_ninos',
            field=models.CharField(blank=True, help_text='Edades separadas por comas, por ejemplo: 5, 11', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CotizacionDestino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField()),
                ('orden', models.PositiveIntegerField(default=1)),
                ('precio_manual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notas', models.TextField(blank=True)),
                ('nombre_destino', models.CharField(blank=True, max_length=180)),
                ('ubicacion_destino', models.CharField(blank=True, max_length=255)),
                ('descripcion_historica', models.TextField(blank=True)),
                ('imagen_destino', models.CharField(blank=True, max_length=500)),
                ('nombre_tour', models.CharField(blank=True, max_length=180)),
                ('duracion_tour', models.CharField(blank=True, max_length=120)),
                ('punto_encuentro', models.CharField(blank=True, max_length=255)),
                ('incluye', models.TextField(blank=True)),
                ('no_incluye', models.TextField(blank=True)),
                ('itinerario', models.TextField(blank=True)),
                ('recomendaciones', models.TextField(blank=True)),
                ('que_llevar', models.TextField(blank=True)),
                ('restricciones', models.TextField(blank=True)),
                ('politica_cancelacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='sami_admin.cotizacion')),
                ('lugar_turistico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paradas_cotizadas', to='sami_admin.lugarturistico')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paradas_cotizadas', to='sami_admin.tour')),
            ],
            options={
                'ordering': ('fecha_visita', 'orden', 'id'),
                'indexes': [models.Index(fields=['cotizacion', 'fecha_visita', 'orden'], name='sami_admin__cotizac_61811f_idx')],
            },
        ),
    ]
