# Generated by Django 4.2.30 on 2026-08-30 17:42

from django.db import migrations, models
from django.utils.text import slugify


def populate_public_slugs(apps, schema_editor):
    LugarTuristico = apps.get_model("sami_admin", "LugarTuristico")
    Tour = apps.get_model("sami_admin", "Tour")

    for model, queryset, label_builder in (
        (
            LugarTuristico,
            LugarTuristico.objects.select_related("departamento"),
            lambda item: f"{item.nombre}-{item.departamento.nombre}",
        ),
        (
            Tour,
            Tour.objects.select_related("lugar_turistico"),
            lambda item: f"{item.nombre_comercial}-{item.lugar_turistico.nombre}",
        ),
    ):
        used = set(model.objects.exclude(slug__isnull=True).values_list("slug", flat=True))
        for item in queryset.filter(slug__isnull=True):
            base = slugify(label_builder(item))[:200] or f"item-{item.pk}"
            candidate = base
            suffix = 2
            while candidate in used:
                candidate = f"{base[:214]}-{suffix}"
                suffix += 1
            item.slug = candidate
            item.save(update_fields=["slug"])
            used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0009_convert_superusers_to_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='resumen_publico',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='slug',
            field=models.SlugField(max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='en_promocion',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=220, null=True, unique=True),
        ),
        migrations.RunPython(populate_public_slugs, migrations.RunPython.noop),
    ]
