# Generated by Django 4.2.30 on 2026-08-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0010_lugarturistico_destacado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lugarturistico',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
    ]
