# Generated by Django 4.2.30 on 2026-08-30 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sami_admin', '0011_alter_lugarturistico_slug_alter_tour_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre interno para identificar la campaña.', max_length=120)),
                ('etiqueta', models.CharField(default='Promoción especial', help_text='Texto corto que aparece sobre el título.', max_length=80)),
                ('titulo', models.CharField(max_length=140)),
                ('descripcion', models.TextField(max_length=360)),
                ('imagen_escritorio', models.ImageField(upload_to='campanas/escritorio/')),
                ('imagen_movil', models.ImageField(upload_to='campanas/movil/')),
                ('texto_alternativo', models.CharField(help_text='Describe brevemente la imagen para accesibilidad.', max_length=180)),
                ('texto_boton', models.CharField(default='Solicitar cotización', max_length=50)),
                ('tipo_enlace', models.CharField(choices=[('cotizador', 'Formulario de cotización'), ('destino', 'Destino turístico'), ('tour', 'Tour o paquete'), ('personalizado', 'Enlace personalizado')], default='cotizador', max_length=20)),
                ('url_personalizada', models.URLField(blank=True)),
                ('fecha_inicio', models.DateTimeField(db_index=True)),
                ('fecha_fin', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('prioridad', models.PositiveSmallIntegerField(default=10, help_text='La campaña activa con el número más alto se mostrará primero.')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('mostrar_avion', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_creadas', to=settings.AUTH_USER_MODEL)),
                ('lugar_turistico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='sami_admin.lugarturistico')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas', to='sami_admin.tour')),
            ],
            options={
                'verbose_name': 'campaña promocional',
                'verbose_name_plural': 'campañas promocionales',
                'ordering': ('-prioridad', '-fecha_inicio', '-id'),
            },
        ),
    ]
