# Generated by Django 4.2.30 on 2026-08-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0012_campanapromocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='actividades_destacadas',
            field=models.TextField(blank=True, help_text='Una actividad por línea.'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='aeropuerto_principal',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='duracion_recomendada',
            field=models.CharField(blank=True, help_text='Ejemplo: 4 a 6 días.', max_length=120),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='mejor_epoca',
            field=models.CharField(blank=True, help_text='Meses o temporada recomendada para visitar el destino.', max_length=180),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='requisitos_viaje',
            field=models.TextField(blank=True, help_text='Orientación general; evita afirmar requisitos que puedan cambiar.'),
        ),
    ]
