# Generated by Django 4.2.30 on 2026-09-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0015_campaign_multimedia_archive_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='idioma_documento',
            field=models.CharField(choices=[('es', 'Español'), ('en', 'English')], default='es', max_length=2),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='actividades_destacadas_en',
            field=models.TextField(blank=True, verbose_name='Actividades destacadas en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='descripcion_historica_en',
            field=models.TextField(blank=True, verbose_name='Descripción histórica en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='duracion_recomendada_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Duración recomendada en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='mejor_epoca_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Mejor época en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='nombre_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nombre en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='requisitos_viaje_en',
            field=models.TextField(blank=True, verbose_name='Requisitos de viaje en inglés'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='resumen_publico_en',
            field=models.CharField(blank=True, max_length=280, verbose_name='Resumen público en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duracion_en',
            field=models.CharField(blank=True, max_length=120, verbose_name='Duración en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='incluye_en',
            field=models.TextField(blank=True, verbose_name='Incluye en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='itinerario_en',
            field=models.TextField(blank=True, verbose_name='Itinerario en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='no_incluye_en',
            field=models.TextField(blank=True, verbose_name='No incluye en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nombre_comercial_en',
            field=models.CharField(blank=True, max_length=180, verbose_name='Nombre comercial en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='politica_cancelacion_en',
            field=models.TextField(blank=True, verbose_name='Política de cancelación en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='punto_encuentro_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Punto de encuentro en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='que_llevar_en',
            field=models.TextField(blank=True, verbose_name='Qué llevar en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='recomendaciones_en',
            field=models.TextField(blank=True, verbose_name='Recomendaciones en inglés'),
        ),
        migrations.AddField(
            model_name='tour',
            name='restricciones_en',
            field=models.TextField(blank=True, verbose_name='Restricciones en inglés'),
        ),
    ]
