# Generated by Django 4.2.30 on 2026-09-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0016_cotizacion_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('negociacion', 'En negociación'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20),
        ),
    ]
