# Generated by Django 4.2.30 on 2026-09-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0017_alter_cotizacion_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campanapromocional',
            name='clics',
        ),
        migrations.RemoveField(
            model_name='campanapromocional',
            name='conversiones',
        ),
        migrations.RemoveField(
            model_name='campanapromocional',
            name='impresiones',
        ),
    ]
