# Generated by Django 4.2.30 on 2026-09-03 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sami_admin', '0018_remove_campanapromocional_clics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugarturistico',
            name='imagen_foco_x',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición horizontal del punto importante de la imagen, de 0 a 100%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Punto focal horizontal'),
        ),
        migrations.AddField(
            model_name='lugarturistico',
            name='imagen_foco_y',
            field=models.PositiveSmallIntegerField(default=50, help_text='Posición vertical del punto importante de la imagen, de 0 a 100%.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Punto focal vertical'),
        ),
    ]
